export const MODEL_LIST = 'MODEL_LIST';
export const MODEL_LIST_ERROR = 'MODEL_LIST_ERROR';

export const GET_MODEL_LIST = 'GET_MODEL_LIST';
export const GET_MODEL_LIST_ERROR = 'GET_MODEL_LIST_ERROR';

export const GET_CATEGORIES_LIST = 'GET_CATEGORIES_LIST';
export const GET_CATEGORIES_LIST_ERROR = 'GET_CATEGORIES_LIST_ERROR';

export const NETWORK_ERROR = 'NETWORK_ERROR';
